{{ if .Values.services.pgweb.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: pizza-db-seed
  labels:
    app: pizza-db-seed
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: pizza-db-seed
    spec:
      containers:
        - name: seed
          image: "{{ .Values.image.repository }}{{ .Values.jobs.pizza_db_seed.image }}:{{ .Values.image.tag }}"
          env:
            - name: CONNECTION_STRING
              value: "Host={{ .Values.services.postgres.container.host }};Database={{ .Values.services.postgres.database }};"
            - name: Logging__LogLevel__Default
              value: Information
              
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secrets
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secrets
                  key: password  
          
      restartPolicy: OnFailure
  
{{ end }}