apiVersion: batch/v1
kind: Job
metadata:
  name: pizza-db-migrations
  labels:
    app: pizza-db-migrations
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: pizza-db-migrations
    spec:
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}{{ .Values.jobs.pizza_db_migrations.image }}:{{ .Values.image.tag }}"
          env:
            - name: CONNECTION_STRING
              value: "Host={{ .Values.services.postgres.container.host }};Database={{ .Values.services.postgres.database }};"
            
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secrets
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secrets
                  key: password  
          
      restartPolicy: OnFailure
  