apiVersion: v1
kind: Service
metadata:
  name: pizza-db-postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.postgres.container.port }}
      targetPort: {{ .Values.services.postgres.container.port }}
  selector:
    app: pizza-db-postgres
