apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Pizza-Ordering-System
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: example
  lifecycle: experimental
  owner: medoni