{{ if eq .Values.global.ingress "traefik" }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ir-pizza-service
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pizza-service.{{ .Values.global.domain }}`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: pizza-service
          port: {{ .Values.services.pizza_service.container.port }}
      middlewares:
        - name: irm-pizza-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pizza-service-ingress
spec:
  rules:
    - host: pizza-service.{{ .Values.global.domain }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: pizza-service
                port:
                  number: {{ .Values.services.pizza_service.container.port }}
          - path: /api/*
            pathType: Prefix
            backend:
              service:
                name: pizza-service
                port:
                  number: {{ .Values.services.pizza_service.container.port }}

{{ end }}
