name: 'Playwright E2E Tests'
description: 'Run Playwright E2E tests'

inputs:
  working-directory:
    description: 'Directory containing the tests'
    required: false
    default: 'tests'
  browser:
    description: 'Browser to run tests on'
    required: false
    default: 'chromium'

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Install Playwright
      shell: bash
      run: |
        pnpm i
        npx playwright install --with-deps ${{ inputs.browser }}
      working-directory: ${{ inputs.working-directory }}

    - name: Run Playwright tests
      shell: bash
      run: |
        pnpm exec playwright test
      working-directory: ${{ inputs.working-directory }}
