
global:
  domain: dev-local.pos.mycluster.localhost

image:
  repository: ghcr.io/medoni/2024-helm-microservice-deployment/
  tag: pr-d44450cfb1bb7bb1bf20f2db73b12a9d2c6e5a8a

services:
  pizza_ordering_service:  # todo: rename
    image: pizza-ordering-service # default
    container:
      port: 8080 # default

  pgweb:
    enabled: true
    image: sosedoff/pgweb # default
    tag: 0.15.0 # default
    container:
      port: 8081 # default
  
  postgres:
    image: postgres # default
    tag: 16.4 # default
    container:
      host: postgres
      port: 5432 # default, /postres.port
    database: pizza_ordering
