
global:
  domain: dev-local.pos.mycluster.localhost

image:
  repository: registry.mycluster.localhost/
  tag: latest

services:
  pizza_ordering_service:
    image: pizza-ordering-service # default
    container:
      port: 8080 # default

  pgweb:
    enabled: true
    image: sosedoff/pgweb # default
    tag: 0.15.0 # default
    container:
      port: 8081 # default
  
  postgres:
    image: postgres # default
    tag: 16.4 # default
    container:
      host: postgres
      port: 5432 # default, /postres.port
    database: pizza_ordering
