
global:
  domain: dev-local.pos.mycluster.localhost

image:
  repository: registry.mycluster.localhost/
  tag: latest

services:
  pizza_service:
    image: pizza-service # default
    container:
      port: 8080 # default

  pgweb:
    enabled: true
    image: sosedoff/pgweb # default
    tag: 0.15.0 # default
    container:
      port: 8081 # default
  
  postgres:
    image: postgres # default
    tag: 16.4 # default
    container:
      host: pizza-db-postgres
      port: 5432 # default, /postres.port
    database: pizza_service # default

jobs:
  pizza_db_migrations:
    image: pizza-db-migrations # default
  pizza_db_seed:
    enabled: true
    image: pizza-db-seed # default
