apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: 2024-helm-microservice-deployment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Example project for the deployment of a single control chart across multiple environments
  sourceRepos:
  - '*'
  destinations:
  - namespace: 2024-helm-microservice-deployment
    server: https://kubernetes.default.svc
