apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ir-pizza-ordering-service
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pizza-ordering-service.{{ .Values.global.domain }}`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: pizza-ordering-service
          port: {{ .Values.services.pizza_ordering_service.container.port }}
      middlewares:
        - name: irm-pizza-ordering-service
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: irm-pizza-ordering-service
spec:
  stripPrefix:
    prefixes:
      - /api
