apiVersion: v1
kind: Service
metadata:
  name: pizza-ordering-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.pizza_ordering_service.container.port }}
      targetPort: {{ .Values.services.pizza_ordering_service.container.port }}
  selector:
    app: pizza-ordering-service
