apiVersion: v1
kind: Service
metadata:
  name: pizza-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.pizza_service.container.port }}
      targetPort: {{ .Values.services.pizza_service.container.port }}
  selector:
    app: pizza-service
