apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pos-devlocal-pizzaservice
  namespace: argocd
spec:                                                                                                      
  project: 2024-helm-microservice-deployment
  source:
    repoURL: https://github.com/medoni/2024-helm-microservice-deployment.git
    targetRevision: master
    path: src/infrastructure/helm/dev-local/PizzaService
  destination:
    server: https://kubernetes.default.svc
    namespace: 2024-helm-microservice-deployment
  syncPolicy:
    automated: {}
