name: Helm integration tests

on:
  workflow_call:

jobs:
  helm-unit-tests:
    name: Helm unit tests
    runs-on: ubuntu-latest
    steps:
    - name: "[SETUP] Checkout code"
      uses: actions/checkout@v4

    - name: "[SETUP] Install Helm"
      uses: azure/setup-helm@v4
    
    - name: "[TEST] Lint Helm chart"
      run: |
        helm lint ./src/infrastructure/Kubernetes/helm/dev-local/PizzaService
    
    - name: "[Test] Run tests"
      run: |
        helm plugin install https://github.com/helm-unittest/helm-unittest.git --version 0.3.3 &> /dev/null
        helm unittest ./src/infrastructure/helm/dev-local/PizzaService
