name: Documentation Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy-techdocs:
    name: Build and deploy documentation to github pages
    uses: ./.github/workflows/_techdocs.yaml
    with:
      deploy: true
    secrets: inherit
    